version: '3.9'

services:
  mariadb:
    image: 'mariadb:latest'
    container_name: mariadb
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    ports:
      - '3305:3306' # Local: Map port 3305 on the host to 3306 in the container
    networks:
      - app-network
    restart: always
    deploy: # Deployment-specific settings
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    container_name: phpmyadmin
    environment:
      - 'PMA_HOST=mariadb' # Connect phpMyAdmin to MariaDB
      - 'PMA_USER=myuser'
      - 'PMA_PASSWORD=secret'
      - 'PMA_ABSOLUTE_URI=http://127.0.0.1:8080/' # Update for deployment URL if needed
    ports:
      - '8080:80' # Local: Expose phpMyAdmin on port 8080
    networks:
      - app-network
    restart: always
    deploy: # Deployment-specific settings
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devroomtrial-backend
    ports:
      - '8081:8081'
      - '8082:8082'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - mariadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1" # Local binding for development
